import Vue from "vue";

import Icon from "./components/icon";
import Button from "./components/button";
import ButtonGroup from "./components/button-group";
import Input from "./components/input";
import Row from "./components/row";
import Col from "./components/col";
import Tabs from "./components/tabs";
import TabsHead from "./components/tabs-head";
import TabsBody from "./components/tabs-body";
import TabsItem from "./components/tabs-item";
import TabsPane from "./components/tabs-pane";
import Popover from "./components/popover";
import Collapse from "./components/collapse";
import CollapseItem from "./components/collapse-item";
import Sticky from "./components/sticky";
import Cascader from "./components/cascader";
import Card from "./components/card";
import Slides from "./components/slides";
import SlidesItem from "./components/slides-item";
import Nav from "./components/nav";
import SubNav from "./components/sub-nav";
import NavItem from "./components/nav-item";
import BackTop from "./components/backtop";
import Pager from "./components/pager";
import Table from "./components/table";
import TableColumn from "./components/table-column";
import Scroll from "./components/scroll";

// import CascaderItem from "./components/cascader-item";

Vue.component("b-icon", Icon);
Vue.component("b-button", Button);
Vue.component("b-button-group", ButtonGroup);
Vue.component("b-input", Input);
Vue.component("b-row", Row);
Vue.component("b-col", Col);
Vue.component("b-tabs", Tabs);
Vue.component("b-tabs-head", TabsHead);
Vue.component("b-tabs-body", TabsBody);
Vue.component("b-tabs-item", TabsItem);
Vue.component("b-tabs-pane", TabsPane);
Vue.component("b-popover", Popover);
Vue.component("b-collapse", Collapse);
Vue.component("b-collapse-item", CollapseItem);
Vue.component("b-sticky", Sticky);
Vue.component("b-cascader", Cascader);
Vue.component("b-card", Card);
Vue.component("b-slides", Slides);
Vue.component("b-slides-item", SlidesItem);
Vue.component("b-nav-item", NavItem);
Vue.component("b-nav", Nav);
Vue.component("b-sub-nav", SubNav);
Vue.component("b-backtop", BackTop);
Vue.component("b-pager", Pager);
Vue.component("b-table", Table);
Vue.component("b-table-column", TableColumn);
Vue.component("b-scroll", Scroll);
// Vue.component("b-cascader-item", CascaderItem);